FROM bsantanna/java-python-exec
MAINTAINER Bruno Sant'Anna "bruno@btech.software"
ENV CREATED_AT 2019-07-20

RUN apk --update add libffi-dev openblas-dev freetype-dev cython

RUN pip3 install --upgrade numpy scipy matplotlib pandas sympy
