FROM bsantanna/util-math:x86_64
LABEL org.opencontainers.image.authors="bruno@btech.software"
ENV CREATED_AT 2018-12-30

RUN pip3 install --upgrade oauth2client google-api-python-client alpha_vantage quandl
