name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      file:
        required: true
        type: string
      tags:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.tags }}