name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  build_base:
    needs: setup
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: images/base
        file: images/base/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          bsantanna/base:latest
          bsantanna/base:x86_64
          bsantanna/base:amd64
          bsantanna/base:arm64

  build_maven_build:
    needs: build_base
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: images/dev/maven-build
        file: images/dev/maven-build/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          bsantanna/maven-build:latest
          bsantanna/maven-build:x86_64
          bsantanna/maven-build:amd64
          bsantanna/maven-build:arm64