name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: bsantanna/base:x86_64
      run: docker build images/base/arch/x86_64 --file images/base/arch/x86_64/Dockerfile --tag bsantanna/base:x86_64
